FROM golang:1.22-alpine

COPY main /main

ENV POSTGRES_USERNAME=postgres \ 
    POSTGRES_DATABASE=stock \
    POSTGRES_PASSWORD=postgres \
    POSTGRES_PORT=5432 \ 
    POSTGRES_HOST=127.0.0.1

EXPOSE 8080

ENTRYPOINT ["main"]